---
openapi: 3.0.0
info:
  title: Kyivmural API
  description: Kyivmural API
  version: 0.1.0

paths:
  /murals:
    get:
      summary: Returns a list of murals
      responses:
        "200":
          description: A JSON array of mural ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
      security:
        - AwsIamAuthorizer: []

securityDefinitions:
  AwsIamAuthorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: awsSigv4
