---
openapi: 3.0.1
info:
  title: Kyivmural API
  description: Kyivmural API
  version: 0.1.0

paths:
  /murals:
    get:
      summary: Returns a list of murals
      responses:
        "200":
          description: A JSON array of mural ids
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
      security:
        - AwsIamAuthorizer: []

    post:
      summary: Add a new mural
      requestBody:
        description: Mural objects to be added
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Mural"
        required: true
      responses:
        201:
          description: Successful operation
        400:
          description: Bad request, invalid body
        401:
          description: Bad request, authentication problem
        409:
          description: Bad request, conflict
        500:
          desription: Internal server error
      security:
        - AwsIamAuthorizer: []


components:
  securitySchemes:
    AwsIamAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: awsSigv4
