name: Lint cloudformation templates
on:
  push:
    branches-ignore: 
      - master
  pull_request:
    branches:
      - master

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@master
        with:
          args: templates/*.cfn
  
  yaml-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3.0.0
        with:
          file_or_dir: templates/
  
  openapi-linter:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vaibhav-jain/spectral-action@v2.6.1
        with:
          file_path: templates/api-specification.yml
