name: PR pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  pyhon-linter:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: functions
          extra-isort-options: --profile black

  python-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
         with:
           python-version: 3.8
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - name: Install dependencies
        run: pipenv sync --dev
      - name: Add current working dir to PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:src" >> $GITHUB_ENV
      - name: Run unit tests
        run: pipenv run pytest functions/tests/ --cov-report=html --cov=functions/ --cov-fail-under=60
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
          with:
            name: Coverage report
            path: htmlcov/

  cloudformation-linter:
    name: Lint Cloudformation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@master
        with:
          args: templates/*.cfn
      - uses: stelligent/cfn_nag@master
        with:
          input_path: templates/*.cfn
          extra_args: --fail-on-warnings

  yaml-linter:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3.0.0
        with:
          file_or_dir: templates/
  
  openapi-linter:  
    name: Lint OpenaAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vaibhav-jain/spectral-action@v2.6.1
        with:
          file_path: templates/api-specification.yml
  
  provision-pr-stack:
    name: Provision PR stack
    needs:
      - cloudformation-linter
      - yaml-linter
      - openapi-linter
      - pyhon-linter
      - python-unit-tests
    runs-on: ubuntu-latest
    env:
      BRANCH: pr-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KYIVMURAL_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KYIVMURAL_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_KYIVMURAL_REGION }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - name: Install dependencies
        run: pipenv sync
      - name: Add current working dir to PYTHONPATH
        run: echo "PYTHONPATH=${PYTHONPATH}:src" >> $GITHUB_ENV
      - name: Package cloudformation template
        run: pipenv run python ci/package.py --layer-name kyivmural-api --path templates/ --main-template kyivmural-api.cfn --branch $BRANCH --artifacts-bucket $ARTIFACTS_BUCKET --cfn-bucket $CFN_BUCKET
        env:
          ARTIFACTS_BUCKET: ${{ secrets.AWS_KYIVMURAL_ARTIFACTS_BUCKET }}
          CFN_BUCKET: ${{ secrets.AWS_KYIVMURAL_CFN_BUCKET }}
      - name: Provision dev stack
        run: pipenv run python ci/provision.py --template-file templates/kyivmural-api.cfn --layer-name kyivmural-api --branch $BRANCH
